/*
 * UNIVERSIDAD MARIANO GALVEZ
 * INGENIERIA DE SISTEMAS DE INFORMACION
 * SISTEMAS OPERATIVOS 2
 * Gustavo Adolfo Lucas Cifuentes
 * 7690-17-2810
 * Ronal Geovani Perez Atz
 * 7690-14-11506
 * Proyecto 3 
 * Primer  Semestre 2019
 */

package Proyecto3SO2;

import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author glucas & rperez
 */

public class PanelTituloGUI extends javax.swing.JPanel {

    /**
     * Creates new form PanelTitulo
     */
    public PanelTituloGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        Accion = new javax.swing.JLabel();
        Puntos = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(420, 45));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setText("Nombre");

        Accion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Accion.setForeground(new java.awt.Color(255, 255, 255));
        Accion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Accion.setText("Acción");

        Puntos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Puntos.setForeground(new java.awt.Color(255, 255, 255));
        Puntos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Puntos.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Accion, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre)
                    .addComponent(Accion)
                    .addComponent(Puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Accion;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Puntos;
    // End of variables declaration//GEN-END:variables

    public void setAccion(String Accion) {
        this.Accion.setText(Accion);
        if (Accion=="Espera"){
            this.Accion.setForeground(Color.red);
        } else {
            this.Accion.setForeground(Color.green);
        }
    }

    public void setNombre(String Nombre) {
        this.Nombre.setText(Nombre);
    }

    public void setPuntos(String Puntos) {
        this.Puntos.setText(Puntos);
    }
}
